# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ninfo.proto\"\xa5\x02\n\x08\x44\x61taInfo\x12\x14\n\x0cinput_folder\x18\x01 \x03(\t\x12\x15\n\routput_folder\x18\x02 \x01(\t\x12\x17\n\x06\x64\x65vice\x18\x03 \x01(\x0b\x32\x07.Device\x12\x14\n\x0csource_model\x18\x04 \x01(\t\x12\n\n\x02\x66s\x18\x05 \x01(\x01\x12\x0c\n\x04nfft\x18\x06 \x01(\x05\x12\t\n\x01\x44\x18\x07 \x01(\x05\x12\x0b\n\x03SNR\x18\x08 \x01(\x01\x12\t\n\x01J\x18\t \x01(\x05\x12\x0f\n\x04\x62\x65ta\x18\n \x01(\x05:\x01\x30\x12\x12\n\x04runs\x18\x0b \x01(\x05:\x04\x35\x30\x30\x30\x12\x18\n\x0c\x61\x63\x63uracy_bin\x18\x0c \x01(\x05:\x02\x31\x30\x12\x10\n\x08\x64uration\x18\r \x01(\x01\x12\x19\n\x07summary\x18\x0e \x01(\x0b\x32\x08.Results\x12\x14\n\x0ctrain_folder\x18\x0f \x01(\t\"\x8e\x02\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10impulse_response\x18\x02 \x01(\t\x12\x15\n\rfreq_response\x18\x03 \x01(\t\x12\x0b\n\x03mic\x18\x04 \x01(\x05\x12\n\n\x02\x66\x30\x18\x05 \x01(\x01\x12\x0b\n\x03lam\x18\x06 \x01(\x01\x12\x0b\n\x03gam\x18\x07 \x01(\x01\x12\x33\n\x08multires\x18\x08 \x01(\x0b\x32!.Device.MultiresolutionParameters\x1a]\n\x19MultiresolutionParameters\x12\x0b\n\x03lam\x18\x01 \x01(\x01\x12\x0b\n\x03gam\x18\x02 \x01(\x01\x12\x10\n\x05top_k\x18\x03 \x01(\x05:\x01\x37\x12\x14\n\tneighbors\x18\x04 \x01(\x05:\x01\x34\"M\n\x07Results\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x01\x12\x13\n\x0brobust_mean\x18\x02 \x01(\x01\x12\x1b\n\x13\x61\x63\x63uracy_per_source\x18\x03 \x01(\x01')
)




_DATAINFO = _descriptor.Descriptor(
  name='DataInfo',
  full_name='DataInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_folder', full_name='DataInfo.input_folder', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_folder', full_name='DataInfo.output_folder', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='DataInfo.device', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_model', full_name='DataInfo.source_model', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fs', full_name='DataInfo.fs', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nfft', full_name='DataInfo.nfft', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='D', full_name='DataInfo.D', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SNR', full_name='DataInfo.SNR', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='J', full_name='DataInfo.J', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta', full_name='DataInfo.beta', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='runs', full_name='DataInfo.runs', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy_bin', full_name='DataInfo.accuracy_bin', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='DataInfo.duration', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summary', full_name='DataInfo.summary', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_folder', full_name='DataInfo.train_folder', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=308,
)


_DEVICE_MULTIRESOLUTIONPARAMETERS = _descriptor.Descriptor(
  name='MultiresolutionParameters',
  full_name='Device.MultiresolutionParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lam', full_name='Device.MultiresolutionParameters.lam', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gam', full_name='Device.MultiresolutionParameters.gam', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='top_k', full_name='Device.MultiresolutionParameters.top_k', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=7,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='Device.MultiresolutionParameters.neighbors', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=581,
)

_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Device.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='impulse_response', full_name='Device.impulse_response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='freq_response', full_name='Device.freq_response', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mic', full_name='Device.mic', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='f0', full_name='Device.f0', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lam', full_name='Device.lam', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gam', full_name='Device.gam', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multires', full_name='Device.multires', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DEVICE_MULTIRESOLUTIONPARAMETERS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=581,
)


_RESULTS = _descriptor.Descriptor(
  name='Results',
  full_name='Results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='Results.accuracy', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robust_mean', full_name='Results.robust_mean', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy_per_source', full_name='Results.accuracy_per_source', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=660,
)

_DATAINFO.fields_by_name['device'].message_type = _DEVICE
_DATAINFO.fields_by_name['summary'].message_type = _RESULTS
_DEVICE_MULTIRESOLUTIONPARAMETERS.containing_type = _DEVICE
_DEVICE.fields_by_name['multires'].message_type = _DEVICE_MULTIRESOLUTIONPARAMETERS
DESCRIPTOR.message_types_by_name['DataInfo'] = _DATAINFO
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['Results'] = _RESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataInfo = _reflection.GeneratedProtocolMessageType('DataInfo', (_message.Message,), dict(
  DESCRIPTOR = _DATAINFO,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:DataInfo)
  ))
_sym_db.RegisterMessage(DataInfo)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(

  MultiresolutionParameters = _reflection.GeneratedProtocolMessageType('MultiresolutionParameters', (_message.Message,), dict(
    DESCRIPTOR = _DEVICE_MULTIRESOLUTIONPARAMETERS,
    __module__ = 'info_pb2'
    # @@protoc_insertion_point(class_scope:Device.MultiresolutionParameters)
    ))
  ,
  DESCRIPTOR = _DEVICE,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:Device)
  ))
_sym_db.RegisterMessage(Device)
_sym_db.RegisterMessage(Device.MultiresolutionParameters)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), dict(
  DESCRIPTOR = _RESULTS,
  __module__ = 'info_pb2'
  # @@protoc_insertion_point(class_scope:Results)
  ))
_sym_db.RegisterMessage(Results)


# @@protoc_insertion_point(module_scope)
